INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Perseverance", "Endure.", "all-secret-perseverance", "s.map.drain > 420");; -- Pass any map that is 7+ minutes long. NOTE: Contrary to most other medals, the map must meet the above criteria BEFORE applying any optional mods. NOTE: Make sure you are looking at the map's drain time and not the total runtime! You can see a map's drain time by hovering your mouse over the runtime on the map's beatmap page.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Feel The Burn", "It isn't all about how fast you manage.", "all-secret-ftb", "s.map.drain > 420 and s.perfect"); -- FC any map that is 7+ minutes long. NOTE: Contrary to most other medals, the map must meet the above criteria BEFORE applying any optional mods. NOTE: Make sure you are looking at the map's drain time and not the total runtime! You can see a map's drain time by hovering your mouse over the runtime on the map's beatmap page.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Just One Second", "And suddenly.. gone.", "all-secret-onesecond", "s.mods.has_all(Mods.HIDDEN, Mods.FLASHLIGHT) and s.map.ar >= 9"); -- Pass any map that is AR9 or above, using the mods above.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Up For The Challenge", "Turn it up to eleven.", "all-secret-challenge", "s.perfect and s.mods & Mods.HARDROCK and s.map.ar >= 7.2 and s.map.hp >= 7.2 and s.map.od >= 7.2"); -- FC any map that is AR10, OD10, and HP10, using HR. NOTE: The map must be at least AR7.2, OD7.2, and HP7.2 before HR. Additional mods (e.x. DT) do not change the fact that the map must meet the above requirements with HR only.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Realität", "A moonlight butterfly, and beacons of three.", "all-secret-realitat", "s.map.map_id == 529285 and s.accuracy > 90"); -- Pass LeaF - Evanescent with 90%+ accuracy.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Our Mechanical Benefactors", "Human, please explain directive 'GREED'.", "all-secret-ourbenefactors", "s.map.map_id == 260489 and s.accuracy > 85"); -- Pass Traktion - The Near Distant Future with 85%+ accuracy.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Elite", "Dangerous beat agents.", "all-secret-elite", "s.max_combo == 1337 and s.map.stars >= 3.5 and s.map.ar >= 8 and s.map.od >= 8"); -- Get 1337 combo on any map that is at least 3.5*, AR8, OD8, and has at least 1500 max combo. NOTE: Contrary to most other medals, the map must meet the above criteria BEFORE applying any optional mods. NOTE: If you are playing in a gamemode that does not have AR (mania or taiko), the map's AR is still a requirement; check Bathbot / osu!api or the map's .osu file to find the "AR" of the map you are trying to play.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("50/50", "Half full or half empty, that's a whole lot of fifty.", "all-secret-5050", "s.count_50 == 50"); -- Get 50 50's on any map.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("The Girl in the Forest", "Not even the Elite Four could stop you now.", "all-secret-girlintheforest", "s.map.map_id == 128718 and s.max_combo == 151 and s.accuracy >= 95"); -- Get 151 max combo and 95%+ accuracy on S3RL - Pika Girl.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("You Can't Hide", "I will find you, and I will click you. All of you.", "all-secret-youcanthide", "s.perfect and s.mods.has_all(Mods.HIDDEN, Mods.FLASHLIGHT)"); -- FC any 4*+ map, using the mods above.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Too Fast, Too Furious", "A march if you have eight feet, maybe!", "all-secret-toofasttoofurious", "s.map.set_id == 486142 and s.mods.has_any(Mods.NIGHTCORE, Mods.DOUBLETIME)"); -- Pass any difficulty of cYsmix - Fright March, with either of the mods above. NOTE: Using other mods alongside DT/NC (e.x. HDDT, DTHR) is allowed.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Feelin' It", "Got with the times.", "all-secret-feelinit", "s.map.bpm == s.max_combo or (s.map.bpm / 2) == s.max_combo"); -- Set a score in which your max combo is the same as the map's BPM (or half of it).
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Overconfident", "Try again later, maybe?", "osu-secret-overconfident", "s.mode == Mode.OSU and s.accuracy < 70 and s.mods.has_any(Mods.DOUBLETIME, Mods.NIGHTCORE, Mods.HIDDEN, Mods.FLASHLIGHT, Mods.HARDROCK)"); -- Pass any map with less than 70% accuracy, using ANY of the mods above.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Spooked", "Something moved. It wasn't your cursor!", "osu-secret-spooked", "s.mode == Mode.OSU and s.rank == 'D' and s.mods & Mods.FLASHLIGHT"); -- Pass any map while achieving a D rank, using FL.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("B-Rave", "It takes courage to stand before the master.", "all-secret-brave", "s.map.map_id == 1583147 and s.accuracy > 80"); -- Pass Cranky - T&J with 80%+ accuracy.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Any%", "A speedrunner's best friend.", "all-secret-anypercent", "s.map.set_id == 785774 and s.mods & Mods.DOUBLETIME"); -- Pass any difficulty of LukHash - GLITCH, using DT.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Mirage", "The horizon goes on forever, and ever, and ever...", "all-secret-mirage", "s.map.map_id == 1773372 and s.perfect"); -- FC Culprate - Relucent feat. ZES. NOTE: This is true for all FC-based medals, but is especially pertinent for this medal in particular -- an "FC" in this context means you cannot miss any sliderends. You must get the maximum amount of combo possible on the map.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Under The Stars", "Onwards, to where the darkness can never stop us.", "all-secret-underthestars", "s.map.title == 'Journey' and s.map.artist == 'Phonetic' and s.map.stars > 4 and s.mods.has_all(Mods.FLASHLIGHT, Mods.HIDDEN)"); -- Pass any 4*+ difficulty of Phonetic - Journey, using the mods above.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Senseless", "I hear nothing. I see nothing.", "all-secret-senseless", "s.map.title == 'Silence' and s.map.artist == 'Gourski x Himmes' and s.map.stars > 4 and s.mods & Mods.HIDDEN"); -- Pass any 4*+ difficulty of Gourski x Himmes - Silence, using HD.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Upon The Wind", "And in that gale, no eye could hope to follow.", "all-secret-uponthewind", "s.map.title == 'Hanaarashi' and s.map.artist == 'Cranky' and s.map.stars > 4 and s.mods & Mods.HIDDEN"); -- Pass any 4*+ difficulty of Cranky - Hanaarashi, using HD.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Efflorescence", "A lament for the past, and a glimpse into tomorrow.", "all-secret-efflorescence", "s.map.map_id == 994518"); -- Pass sakuraburst - cherry blossoms explode across the dying horizon.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Inundate", "Swept away.", "all-secret-inundate", "s.map.map_id == 1960198 and s.accuracy > 85 and s.mods & Mods.DOUBLETIME"); -- Pass tieff - Waterflow with with 85%+ accuracy, using DT.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Eureka!", "By Jove, you've got it!", "all-secret-eureka", "s.map.artist == 'The Flashbulb' and s.map.stars > 4 and s.perfect"); -- FC any 4*+ difficulty of any map by the artist The Flashbulb.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Regicide", "A king no more.", "all-secret-regicide", "s.map.map_id in (1582618, 1582621) and s.perfect"); -- FC any 4*+ difficulty of Cranky - Chandelier - King.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Permadeath", "One life, one shot.", "all-secret-permadeath", "s.map.title == 'One Life Left to Live' and s.map.artist == 'antiPLUR' and s.map.stars > 4 and s.mods & Mods.SUDDENDEATH"); -- Pass any 4*+ difficulty of antiPLUR - One Life Left to Live, using SD.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("The Future Is Now", "The stars showed you all that was to come.", "all-secret-futureisnow", "s.map.map_id == 1787848 and s.accuracy > 70"); -- Pass Camellia - Exit This Earth's Atomosphere (Camellia's ''PLANETARY//200STEP'' Remix) with 70%+ accuracy. 
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Natural 20", "Rolled it.", "all-secret-nat20", "s.perfect and s.map.stars > 5 and s.count_300 % 20 == 0"); -- FC any 5*+ map with a play in which your 300 count is a multiple of 20.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("AHAHAHAHA", "TOGETHER FOREVER.", "all-secret-yandere", "s.map.set_id in (744593, 1016769, 959688, 935098)"); -- Pass one difficulty on each of the listed beatmaps.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Lightless", "Better the devil you know.", "all-secret-lightless", "s.map.map_id == 278451 and s.mods & Mods.FLASHLIGHT"); -- Pass LeaF - MEPHISTO [Extra], using FL. NOTE: Playing converted versions of this difficulty is allowed.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Unseen Heights", "Reach for the stars.", "all-secret-unseen-heights", "s.map.stars > 100"); -- Pass any map that is 100*+. NOTE: This medal is doable on converts, so long as the star rating of the convert is 100*+.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Astronomic", "Precision machinery.", "all-secret-astronomic", "s.perfect and s.map.stars > 6 and s.map.artist == 'II-L'"); -- FC any 6*+ difficulty of any map by the artist II-L. NOTE: There is a second (currently broken) way to get this medal that requires an FC on any 5*+ difficulty of any map by the artist II-L using the ScoreV2 mod; this conditional currently does not work, and there is no estimated timeframe for when it will be fixed.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Star Power", "AND I'LL DO IT AGAIN.", "all-secret-star-power", "s.map.map_md5 == s.player.last_score.map.map_md5 and s.map.stars > 4 and s.mods & Mods.HARDROCK and not s.player.last_score.mods & Mods.HARDROCK and s.accuracy == 100"); -- SS a 4*+ map without HR, then SS the same map with HR. NOTE: You MUST get the scores back-to-back; if you fail at any point on the second map, you must restart the medal from the beginning. NOTE: The map may be 
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Jackpot", "Lucky sevens is a mild understatement.", "all-secret-jackpot", "s.score > 100_000 and all(str_score == str(s.score)[0] for str_score in str(s.score))"); -- Complete a map with a score above 100,000, where every digit of the score is the same (222,222 / 7,777,777 / 99,999,999 / etc). Difficulty reduction mods, including NF, are allowed.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Quick Draw", "It's high noon.", "all-secret-quick_draw", "s.map.plays == 0 and s.map.approved & Approved.AWARDS_PP"); -- Be the first to submit a score on any ranked or qualified map.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Nonstop", "Breaks? What are those?", "all-secret-nonstop", "s.perfect and s.map.drain >= 521"); -- Full combo any map that has a drain time of 8:41 or longer (before mods). NOTE: Make sure you are looking at the map's drain time and not the total runtime! You can see a map's drain time by hovering your mouse over the runtime on the map's beatmap page. (Yes, it is actually 8:41, we do not know why lol)
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("The Gradual Rise", "There's no stopping you, is there? Welcome to the top 1,000!", "all-skill-highranker-2", "s.player.rank < 1_000"); -- Reach at least rank 10,000 in the pp rankings of any gamemode.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Scaling Up", "Welcome to the top 100. Never give up!", "all-skill-highranker-3", "s.player.rank < 100"); -- Reach at least rank 5,000 in the pp rankings of any gamemode.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Approaching The Summit", "Pro tier. Welcome to the top 50!", "all-skill-highranker-4", "s.player.rank < 50"); -- Reach at least rank 1,000 in the pp rankings of any gamemode.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Time Dilation", "Longer is shorter when all is said and done.", "all-secret-tidi", "(s.map.drain * 1.5) >= 480 and s.mods.has_any(Mods.DOUBLETIME, Mods.NIGHTCORE) and not s.mods & Mods.NOFAIL"); -- Pass any map that is 8 minutes or longer (after mods), using either of the mods above. NF is not allowed, but all other non-conflicting difficulty reducing mods are. NOTE: This means the map must be at least 12 minutes before DT/NC is applied. NOTE: Make sure you are looking at the map's drain time and not the total runtime! You can see a map's drain time by hovering your mouse over the runtime on the map's beatmap page.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("To The Core", "In for a penny, in for a pound. Pounding bass, that is.", "all-secret-tothecore", "('nightcore' in s.map.artist.lower() or 'nightcore' in s.map.title.lower()) and s.mods.has_any(Mods.DOUBLETIME, Mods.NIGHTCORE)"); -- Pass any map that contains 'nightcore' in the title or artist name, using either of the mods above. Difficulty reduction mods are not allowed, despite the category the medal is in.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Prepared", "Do it for real next time.", "all-secret-prepared", "s.perfect and s.mods & Mods.NOFAIL"); -- FC any map, using NF.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Reckless Abandon", "Throw it all to the wind.", "all-secret-reckless", "s.perfect and s.map.stars > 3 and s.mods.has_all(Mods.SUDDENDEATH, Mods.HARDROCK)"); -- FC any 3*+ map, using the mods above.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Lights Out", "The party's just getting started.", "all-secret-lightsout", "s.mods.has_all(Mods.NIGHTCORE, Mods.FLASHLIGHT)"); -- Pass any map, using the mods above.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Camera Shy", "Stop being cute.", "all-secret-uguushy", "s.perfect and s.mods.has_all(Mods.HIDDEN, Mods.NOFAIL)"); -- FC any map, using the mods above.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Hour Before The Dawn", "Eleven skies of everlasting sunrise.", "all-secret-hourbeforethedawn", "s.perfect and s.map.set_id == 151720"); -- FC any difficulty of ginkiha - EOS.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Slow And Steady", "Win the race, or start again.", "all-secret-slowandsteady", "s.perfect and s.map.stars > 3 and s.mods.has_all(Mods.PERFECT, Mods.HALFTIME)"); -- FC any 3*+ map, using the mods above.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("No Time To Spare", "Places to be, things to do.", "all-secret-ntts", "s.perfect and s.mods & Mods.DOUBLETIME and (s.drain * 1.5) <= 30"); -- FC any map, using DT, that is 30 seconds or shorter after mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Sognare", "A dream in stop-motion, soon forever gone.", "all-secret-sognare", "s.map.map_id == 529285 and s.mods & Mods.HALFTIME"); -- Pass LeaF - Evanescent, using HT. Difficulty reduction mods, including NF, are allowed.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Realtor Extraordinaire", "An acre-wide stride.", "all-secret-realtor", "s.map.artist == 'cYsmix' and s.map.title == 'House With Legs' and s.mods.has_all(Mods.DOUBLETIME, Mods.HARDROCK)"); -- FC any difficulty of cYsmix - House With Legs, using the mods above.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Impeccable", "Speed matters not to the exemplary.", "all-secret-impeccable", "s.map.stars > 4 and s.mods.has_all(Mods.DOUBLETIME, Mods.PERFECT)"); -- Pass any 4*+ map, using the mods above.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Quick Maths", "Beats per minute over... this isn't quick at all!", "all-secret-quickmaffs", "s.count_miss == 34 and s.map.set_id == 751774"); -- Get exactly 34 misses on any difficulty of Function Phantom - Variable.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Kaleidoscope", "So many pretty colours. Most of them red.", "all-secret-kaleidoscope", "s.map.map_id == 2022237 and s.accuracy >= 80 and s.mods.has_all(Mods.EASY, Mods.HALFTIME)"); -- Pass The Flashbulb - DIDJ PVC [EX III] with 80% accuracy or higher, using the mods above.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Valediction", "One last time.", "all-secret-valediction", "s.map.map_id == 2202493 and s.accuracy >= 90"); -- Pass a_hisa - Alexithymia | Lupinus | Tokei no Heya to Seishin Sekai with 90% accuracy or higher. Difficulty reduction mods, including NF, are allowed.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Ten To One", "From one extreme to another.", "all-secret-tentoone", "s.player.last_score.map.drain > 600 and s.map.drain <= 60"); -- Pass a map that is 10 minutes or longer, then pass a map that is 1 minute or shorter. NOTE: DT is allowed, just make sure that the map is longer than 10 minutes before you apply mods. NOTE: Make sure you are looking at the map's drain time and not the total runtime! You can see a map's drain time by hovering your mouse over the runtime on the map's beatmap page.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Exquisite", "Indubitably.", "all-secret-exquisite", "s.player.last_score.perfect and s.player.last_score.map.stars > 3 and s.player.last_score.map_md5 != s.map.map_md5 and s.map.stars > 3"); -- FC 2 different 3*+ maps in a row, using either of the mods above. (fuck the mods i dont care )
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Persistence Is Key", "Don't let your dreams be dreams.", "all-secret-persistenceiskey", ""); -- Fail any difficulty of Thaehan - Never Give Up five times, and then pass it. Difficulty reduction mods, including NF, are allowed. NOTE: Each failed play must have at least 10,000 score for it to count as a play.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Not Again", "Regret everything.", "all-secret-notagain", "s.map.artist == 'ARForest' and s.map.title == 'Regret' and s.accuracy >= 99 and s.count_miss == 1"); -- Get 1xMiss and 99%+ accuracy on ARForest - Regret.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Deliberation", "The challenge remains.", "all-secret-deliberation", "s.map.stars >= 6 and s.map.approved & Approved.HAS_LEADERBOARD and s.mods & Mods.HALFTIME"); -- FC any map, with HT, that is 6*+ after mods. NOTE: Using additional mods (e.x. HTHR) is allowed.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("When You See It", "Three numbers which will haunt you forevermore.", "all-secret-when-you-see-it", "s.map.artist == 'xi' and str(round(s.accuracy, 2)).endswith('7.27')"); -- Pass any map by the artist xi with X7.27% accuracy (97.27%, 87.27%, etc). NOTE: There is a separate artist named 'Xi', with a capital X -- that is a different person, and their maps do not count for this medal.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Clarity", "And yet in our memories, you remain crystal clear.", "all-secret-clarity", "s.map.map_id == 1480798"); -- Pass rrtyui's mapset of Camellia vs Akira Complex - Reality Distortion. Difficulty reduction mods, including NF, are allowed.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Autocreation", "Absolute rule.", "all-secret-autocreation", "s.map.creator == s.map.artist"); -- Pass any map in which the artist and the host of the mapset are the same person. Difficulty reduction mods, including NF, are allowed.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Finality", "High stakes, no regrets.", "all-intro-suddendeath", "s.mods == Mods.SUDDENDEATH"); -- Pass any map with the following mod. Can't use any other mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Perfectionist", "Accept nothing but the best.", "all-intro-perfect", "s.mods == Mods.PERFECT"); -- Pass any map with the following mod. Can't use any other mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Rock Around The Clock", "You can't stop the rock.", "all-intro-hardrock", "s.mods == Mods.HARDROCK"); -- Pass any map with the following mod. Can't use any other mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Time And A Half", "Having a right ol' time. One and a half of them, almost.", "all-intro-doubletime", "s.mods == Mods.DOUBLETIME"); -- Pass any map with the following mod. Can't use any other mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Sweet Rave Party", "Founded in the fine tradition of changing things that were just fine as they were.", "all-intro-nightcore", "s.mods == Mods.NIGHTCORE"); -- Pass any map with the following mod. Can't use any other mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Blindsight", "I can see just perfectly.", "all-intro-hidden", "s.mods == Mods.HIDDEN"); -- Pass any map with the following mod. Can't use any other mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Are You Afraid Of The Dark?", "Harder than it looks, probably because it's hard to look.", "all-intro-flashlight", "s.mods == Mods.FLASHLIGHT"); -- Pass any map with the following mod. Can't use any other mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Dial It Right Back", "Sometimes you just want to take it easy.", "all-intro-easy", "s.mods == Mods.EASY"); -- Pass any map with the following mod. Can't use any other mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Risk Averse", "Safety nets are fun!", "all-intro-nofail", "s.mods == Mods.NOFAIL"); -- Pass any map with the following mod. Can't use any other mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Slowboat", "You got there. Eventually.", "all-intro-halftime", "s.mods == Mods.HALFTIME"); -- Pass any map with the following mod. Can't use any other mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Burned Out", "One cannot always spin to win.", "all-intro-spunout", "s.mods == Mods.SPUNOUT"); -- Pass any map with the following mod. Can't use any other mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Resurgence", "A flame rekindled.", "all-secret-resurgence", "('ashes' in s.player.last_score.map.title) and (s.map.artist == 'Panda Eyes & Teminite' and s.map.title == 'Immortal Flame (feat. Anna Yvette)')"); -- Play any map that contains the word "ashes" in the song title, then pass any difficulty of Panda Eyes & Teminite - Immortal Flame (feat. Anna Yvette). Difficulty reduction mods, including NF, are allowed.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Totality", "All the notes. Every single one.", "osu-skill-fc-1", "s.mode == Mode.OSU and s.perfect and 1 <= s.map.stars < 2 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- FC any 1 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Business As Usual", "Two to go, please.", "osu-skill-fc-2", "s.mode == Mode.OSU and s.perfect and 2 <= s.map.stars < 3 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- FC any 2 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Building Steam", "Hey, this isn't so bad.", "osu-skill-fc-3", "s.mode == Mode.OSU and s.perfect and 3 <= s.map.stars < 4 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- FC any 3 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Moving Forward", "Bet you feel good about that.", "osu-skill-fc-4", "s.mode == Mode.OSU and s.perfect and 4 <= s.map.stars < 5 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- FC any 4 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Paradigm Shift", "Surprisingly difficult.", "osu-skill-fc-5", "s.mode == Mode.OSU and s.perfect and 5 <= s.map.stars < 6 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- FC any 5 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Anguish Quelled", "Don't choke.", "osu-skill-fc-6", "s.mode == Mode.OSU and s.perfect and 6 <= s.map.stars < 7 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- FC any 6 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Never Give Up", "Excellence is its own reward.", "osu-skill-fc-7", "s.mode == Mode.OSU and s.perfect and 7 <= s.map.stars < 8 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- FC any 7 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Aberration", "They said it couldn't be done. They were wrong.", "osu-skill-fc-8", "s.mode == Mode.OSU and s.perfect and 8 <= s.map.stars < 9 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- FC any 8 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Chosen", "Reign among the Prometheans, where you belong.", "osu-skill-fc-9", "s.mode == Mode.OSU and s.perfect and 9 <= s.map.stars < 10 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- FC any 9 star map (calculated with mods) without using EZ/NF/HT mods. 
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Unfathomable", "You have no equal.", "osu-skill-fc-10", "s.mode == Mode.OSU and s.perfect and 10 <= s.map.stars < 11 and not s.mods & Mods.EASY and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- FC any 10 star map (calculated with mods) without using EZ/NF/HT mods. 
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Rising Star", "Can't go forward without the first steps.", "osu-skill-pass-1", "s.mode == Mode.OSU and 1 <= s.map.stars < 2 and not s.mods & Mods.EASY and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- Pass any 1 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Constellation Prize", "Definitely not a consolation prize. Now things start getting hard!", "osu-skill-pass-2", "s.mode == Mode.OSU and 2 <= s.map.stars < 3 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- Pass any 2 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Building Confidence", "Oh, you've SO got this.", "osu-skill-pass-3", "s.mode == Mode.OSU and 3 <= s.map.stars < 4 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- Pass any 3 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Insanity Approaches", "You're not twitching, you're just ready.", "osu-skill-pass-4", "s.mode == Mode.OSU and 4 <= s.map.stars < 5 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- Pass any 4 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("These Clarion Skies", "Everything seems so clear now.", "osu-skill-pass-5", "s.mode == Mode.OSU and 5 <= s.map.stars < 6 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- Pass any 5 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Above and Beyond", "A cut above the rest.", "osu-skill-pass-6", "s.mode == Mode.OSU and 6 <= s.map.stars < 7 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- Pass any 6 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Supremacy", "All marvel before your prowess.", "osu-skill-pass-7", "s.mode == Mode.OSU and 7 <= s.map.stars < 8 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- Pass any 7 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Absolution", "My god, you're full of stars!", "osu-skill-pass-8", "s.mode == Mode.OSU and 8 <= s.map.stars < 9 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- Pass any 8 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Event Horizon", "No force dares to pull you under.", "osu-skill-pass-9", "s.mode == Mode.OSU and 9 <= s.map.stars < 10 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- Pass any 9 star map (calculated with mods) without using EZ/NF/HT mods. 
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Phantasm", "Fevered is your passion, extraordinary is your skill.", "osu-skill-pass-10", "s.mode == Mode.OSU and 10 <= s.map.stars < 11 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- Pass any 10 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Thrill of the Chase", "My heart's beating, my hands are shaking, and I'm STILL clicking.", "all-secret-thrillofthechase", "s.mods & Mods.DOUBLETIME or s.mods & Mods.NIGHTCORE and s.map.set_id == 488238 and s.map.stars >= 2.5"); -- FC any difficulty of cYsmix - Classic Pursuit that is 2.5* or higher (after mods), using either of the mods above. NOTE: Using other mods alongside DT/NC (e.x. HDDT, DTHR) is allowed.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("True Torment", "It lasts forever.", "osu-secret-truetorment", "s.mode == Mode.OSU and s.map.map_id == 1257904 and s.accuracy > 70"); -- Pass Helblinde - The Solace of Oblivion with 70%+ accuracy.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Skylord", "Never miss a wingbeat.", "osu-secret-skylord", "s.mode == Mode.OSU and s.accuracy == 100 and s.map.map_id == 1656874"); -- SS James Portland - Sky [Master].
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Vantage", "There we stood, where the spires pierced the sky, and dreamed of the future to come.", "osu-secret-vantage", "s.mode == Mode.OSU and s.map.map_id == 1492654"); -- Pass Culprate & Au5 - Impulse.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Not Bluffing", "Did that with my eyes closed.", "osu-secret-bluffing", "s.mode == Mode.OSU and s.perfect and s.map.set_id == 940377 and s.map.stars > 4 and s.mods.has_all(Mods.HIDDEN, Mods.FLASHLIGHT)"); -- FC any 4*+ difficulty of onumi - ARROGANCE, using the mods above.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Final Boss", "Game over.", "osu-secret-finalboss", "s.mode == Mode.OSU and s.map.map_id == 3333745 and s.accuracy > 92"); -- Pass Yooh - RPG [Divinity] with 92%+ accuracy.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Beast Mode", "Unleash the animal within!", "osu-secret-beastmode", "s.mode == Mode.OSU and s.map.map_id == 2507884 and s.accuracy > 98"); -- Pass meganeko - Feral [Veracious] with 98%+ accuracy.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Mortal Coils", "Never one without the other.", "all-secret-together-apart", "s.map.set_id in (991300, 1198838)"); -- Pass any difficulty of the ranked mapsets of both Fleshgod Apocalypse - The Deceit and Fleshgod Apocalypse - The Violation.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Dark Familiarity", "No mistakes, no witnesses.", "all-secret-dark-familiarity", "s.mods.has_all(Mods.SUDDENDEATH, Mods.HIDDEN) and s.map.map_id == 471598 and s.perfect"); -- FC Maduk ft. Veela - Ghost Assassin (Hourglass Bonusmix) [Lumiere], using the mods above.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Causality", "Definitely not for casuals.", "osu-secret-causality", "s.mode == Mode.OSU and s.map.map_id == 2573493 and s.accuracy > 75"); -- Pass KNOWER - Time Traveler with 75%+ accuracy. NOTE: Remember to enable storyboard and enjoy the experience!
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Abrogation", "Endure not the imposition of celestial law.", "osu-secret-abrogation", "s.mode == Mode.OSU and s.map.map_id == 572525 and s.accuracy > 72"); -- Pass aran - Graces of Heaven with 72%+ accuracy.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Don't let the bunny distract you!", "The order was indeed, not a rabbit.", "all-secret-bunny", "s.perfect and s.map.set_id == 184"); -- FC any difficulty of the map Chatmonchy - Make Up! Make Up!.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Non-stop Dancer", "Can you still feel your feet after that?", "all-secret-dancer", "s.map.map_id == 9007 and s.score > 3_000_000 and not s.mods & Mods.NOFAIL"); -- Pass Yoko Ishida - paraparaMAX I with over 3,000,000 score. NOTE: NF is not allowed, but all other difficulty reducing mods are.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Consolation Prize", "Well, it could be worse.", "all-secret-consolation_prize", "s.rank == 'D' and s.score > 100_000 and s.mods == Mods.NONE"); -- Get a D rank on any map with a play that is above 100,000 score. Using any mods is not allowed. NOTE: In addition to the above, you must have achieved the Most Improved medal before you are able to achieve this medal.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Challenge Accepted", "Oh, you're ON.", "all-secret-challenge_accepted", "s.map.approved == Approved.APPROVED"); -- Pass any approved map. NOTE: This medal is slightly janky and can occasionally not work; nobody knows why. If this medal does not work for you, please consider joining the Exploring Incomplete Medal Solutions forum post in osu! Medal Hunters server! so you can help us figure out why!
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Stumbler", "No regrets.", "all-secret-stumbler", "s.perfect and s.accuracy < 85"); -- FC any map with less than 85% accuracy.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Afterimage", "But a glimpse of its true self.", "osu-secret-afterimage", "s.mode == Mode.OSU and s.mods.has_all(Mods.HALFTIME, Mods.HIDDEN)"); -- Pass any map, using the mods above.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Eclipse", "Something new born from absence.", "osu-secret-eclipse", "s.mode == Mode.OSU and s.mods.has_all(Mods.FLASHLIGHT, Mods.HIDDEN)"); -- Pass any map, using the mods above.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Tunnel Vision", "But it was right there..", "osu-secret-tunnelvision", "s.mode == Mode.OSU and s.mods & Mods.FLASHLIGHT and s.max_combo <= 200"); -- Pass any map, using FL, without getting 200+ combo. Difficulty reduction mods, including NF, are allowed. NOTE: For whatever map you decide to do this on, the sum of the number of circles, double the number of sliders, and triple the number of spinners must be at least 400. Only god knows why this is a requirement.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Behold No Deception", "That wasn't easy at all!", "osu-secret-deception", "s.mode == Mode.OSU and s.perfect and s.mods & Mods.EASY and s.stars > 4.3"); -- FC any map, using EZ, that is 4*+ after mods. ( about 4.3 before eays)
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Dekasight", "So big, yet so hard to see.", "osu-secret-deka", "s.mode == Mode.OSU and s.perfect and s.map.stars > 3 and s.mods.has_all(Mods.EASY, Mods.FLASHLIGHT, Mods.HIDDEN)"); -- FC any 3*+ map, using the mods above.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Meticulous", "The circle goes here, and then here, and then here..", "osu-secret-meticulous", "s.mode == Mode.OSU and s.mods.has_all(Mods.EASY, Mods.PERFECT) and s.map.stars > 3.25"); -- Pass any map, using the mods above, that is 3*+ after mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Infinitesimal", "Big word for something so very, very small.", "osu-secret-infinitesimal", "s.mode == Mode.OSU and s.perfect and s.mods == Mods.HARDROCK and (s.map.cs + s.map.cs * 0.3) > 7.8"); -- FC any map, using HR, that is CS7.8+ after mods. NOTE: Using another mods (e.x. HDHR) is allowed.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Equilibrium", "Balance in all things.", "osu-secret-equilibrium", "s.mode == Mode.OSU and s.count_300 == s.count_100 and s.count_100 == s.count_50 and s.count_300 >= 15"); -- Set a play on any map that achieves an equal number of 300's, 100's, and 50's. NOTE: You must have at least 15 of each.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("In Memoriam", "In loving memory of your sanity, long forgotten.", "osu-secret-inmemoriam", "s.mode == Mode.OSU and s.perfect and s.mods.has_all(Mods.EASY, Mods.FLASHLIGHT, Mods.HALFTIME, Mods.HIDDEN) and s.stars > 4.2"); -- FC any map, using the mods above, that is 4*+ after mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Sanguine", "Timeless thorns still draw blood.", "osu-secret-sanguine", "s.mode == Mode.OSU and s.map.map_id == 131564 and s.accuracy > 92 and s.mods & Mods.EASY"); -- Pass val0108's mapset of Lily - Scarlet Rose with 92%+ accuracy, using EZ.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("5,000 Plays", "There's a lot more where that came from.", "osu-plays-5000", "s.player.play_mode == Mode.OSU and s.player.playcount >= 5_000"); -- Reach 5,000 plays. Your profile on the osu! website will show you how many plays you have so far.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("15,000 Plays", "Must.. click.. circles..", "osu-plays-15000", "s.player.play_mode == Mode.OSU and s.player.playcount >= 15_000"); -- Reach 15,000 plays. Your profile on the osu! website will show you how many plays you have so far.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("25,000 Plays", "There's no going back.", "osu-plays-25000", "s.player.play_mode == Mode.OSU and s.player.playcount >= 25_000"); -- Reach 25,000 plays. Your profile on the osu! website will show you how many plays you have so far.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("50,000 Plays", "You're here forever.", "osu-plays-50000", "s.player.play_mode == Mode.OSU and s.player.playcount >= 50_000"); -- Reach 50,000. Your profile on the osu! website will show you how many plays you have so far.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("500 Combo", "500 big ones! You're moving up in the world!", "osu-combo-500", "s.player.play_mode == Mode.OSU and s.player.max_combo >= 500"); -- Get at least 500 Combo on any beatmap with any mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("750 Combo", "750 notes back to back? Woah.", "osu-combo-750", "s.player.play_mode == Mode.OSU and 500 > s.player.max_combo >= 750"); -- Get at least 750 Combo on any beatmap with any mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("1,000 Combo", "A thousand reasons why you rock at this game.", "osu-combo-1000", "s.player.play_mode == Mode.OSU and 750 > s.player.max_combo >= 1_000"); -- Get at least 1,000 Combo on any beatmap with any mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("2,000 Combo", "Nothing can stop you now.", "osu-combo-2000", "s.player.play_mode == Mode.OSU and 1_000 > s.player.max_combo >= 2_000"); -- Get at least 2,000 Combo on any beatmap with any mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Keeping Time", "Don, then katsu. Don, then katsu..", "taiko-skill-fc-1", "s.mode == Mode.TAIKO and s.perfect and 1 <= s.map.stars < 2 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- FC any 1 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("To Your Own Beat", "Straight and steady.", "taiko-skill-fc-2", "s.mode == Mode.TAIKO and s.perfect and s.perfect and 2 <= s.map.stars < 3 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- FC any 2 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Big Drums", "Bigger scores to match.", "taiko-skill-fc-3", "s.mode == Mode.TAIKO and s.perfect and s.perfect and 3 <= s.map.stars < 4 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- FC any 3 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Adversity Overcome", "Difficult? Not for you.", "taiko-skill-fc-4", "s.mode == Mode.TAIKO and s.perfect and s.perfect and 4 <= s.map.stars < 5 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- FC any 4 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Demonslayer", "An Oni felled forevermore.", "taiko-skill-fc-5", "s.mode == Mode.TAIKO and s.perfect and s.perfect and 5 <= s.map.stars < 6 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- FC any 5 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Rhythm's Call", "Heralding true skill.", "taiko-skill-fc-6", "s.mode == Mode.TAIKO and s.perfect and s.perfect and 6 <= s.map.stars < 7 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- FC any 6 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Time Everlasting", "Not a single beat escapes you.", "taiko-skill-fc-7", "s.mode == Mode.TAIKO and s.perfect and s.perfect and 7 <= s.map.stars < 8 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- FC any 7 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("The Drummer's Throne", "Percussive brilliance befitting royalty alone.", "taiko-skill-fc-8", "s.mode == Mode.TAIKO and s.perfect and s.perfect and 8 <= s.map.stars < 9 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- FC any 8 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("My First Don", "Marching to the beat of your own drum. Literally.", "taiko-skill-pass-1", "s.mode == Mode.TAIKO and 1 <= s.map.stars < 2 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- Pass any 1 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Katsu Katsu Katsu", "Hora! Ikuzo!", "taiko-skill-pass-2", "s.mode == Mode.TAIKO and 2 <= s.map.stars < 3 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- Pass any 2 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Not Even Trying", "Muzukashii? Not even.", "taiko-skill-pass-3", "s.mode == Mode.TAIKO and 3 <= s.map.stars < 4 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- Pass any 3 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Face Your Demons", "The first trials are now behind you, but are you a match for the Oni?", "taiko-skill-pass-4", "s.mode == Mode.TAIKO and 4 <= s.map.stars < 5 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- Pass any 4 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("The Demon Within", "No rest for the wicked.", "taiko-skill-pass-5", "s.mode == Mode.TAIKO and 5 <= s.map.stars < 6 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- Pass any 5 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Drumbreaker", "Too strong.", "taiko-skill-pass-6", "s.mode == Mode.TAIKO and 6 <= s.map.stars < 7 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- Pass any 6 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("The Godfather", "You are the Don of Dons.", "taiko-skill-pass-7", "s.mode == Mode.TAIKO and 7 <= s.map.stars < 8 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- Pass any 7 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Rhythm Incarnate", "Feel the beat. Become the beat.", "taiko-skill-pass-8", "s.mode == Mode.TAIKO and 8 <= s.map.stars < 9 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- Pass any 8 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("30,000 Drum Hits", "Did that drum have a face?", "taiko-hits-30000", "s.player.play_mode == Mode.TAIKO and s.player.total_hits >= 30_000"); -- Reach 30,000 Drum Hits. Your profile on the osu! website will show you how many drum hits you have so far.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("300,000 Drum Hits", "The rhythm never stops.", "taiko-hits-300000", "s.player.play_mode == Mode.TAIKO and s.player.total_hits >= 300_000"); -- Reach 300,000 Drum Hits. Your profile on the osu! website will show you how many drum hits you have so far.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("3,000,000 Drum Hits", "Truly, the Don of dons.", "taiko-hits-3000000", "s.player.play_mode == Mode.TAIKO and s.player.total_hits >= 30_000_000"); -- Reach 3,000,000 Drum Hits. Your profile on the osu! website will show you how many drum hits you have so far.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("30,000,000 Drum Hits", "Your rhythm, eternal.", "taiko-hits-30000000", "s.player.play_mode == Mode.TAIKO and s.player.total_hits >= 300_000_000"); -- Reach 30,000,000 Drum Hits. Your profile on the osu! website will show you how many drum hits you have so far.  
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Anabasis", "And what an adventure you had.", "taiko-secret-anabasis", "s.map.map_id == 2047089"); -- Pass Kikuo - Sight, Noise, Life and the Earth.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Sweet And Sour", "Apples and oranges, literally.", "fruits-skill-fc-1", "s.mode == Mode.CATCH and s.perfect and 1 <= s.map.stars < 2 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- FC any 1 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Reaching The Core", "The seeds of future success.", "fruits-skill-fc-2", "s.mode == Mode.CATCH and s.perfect and 2 <= s.map.stars < 3 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- FC any 2 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Clean Platter", "Clean only of failure. It is completely full, otherwise.", "fruits-skill-fc-3", "s.mode == Mode.CATCH and s.perfect and 3 <= s.map.stars < 4 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- FC any 3 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Between The Rain", "No umbrella needed.", "fruits-skill-fc-4", "s.mode == Mode.CATCH and s.perfect and 4 <= s.map.stars < 5 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- FC any 4 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Addicted", "That was an overdose?", "fruits-skill-fc-5", "s.mode == Mode.CATCH and s.perfect and 5 <= s.map.stars < 6 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- FC any 5 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Quickening", "A dash above normal limits.", "fruits-skill-fc-6", "s.mode == Mode.CATCH and s.perfect and 6 <= s.map.stars < 7 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- FC any 6 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Supersonic", "Faster than is reasonably necessary.", "fruits-skill-fc-7", "s.mode == Mode.CATCH and s.perfect and 7 <= s.map.stars < 8 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- FC any 7 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Dashing Scarlet", "Speed beyond mortal reckoning.", "fruits-skill-fc-8", "s.mode == Mode.CATCH and s.perfect and 8 <= s.map.stars < 9 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- FC any 8 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("A Slice Of Life", "Hey, this fruit catching business isn't bad.", "fruits-skill-pass-1", "s.mode == Mode.CATCH and 1 <= s.map.stars < 2 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- Pass any 1 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Dashing Ever Forward", "Fast is how you do it.", "fruits-skill-pass-2", "s.mode == Mode.CATCH and 2 <= s.map.stars < 3 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- Pass any 2 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Zesty Disposition", "No scurvy for you, not with that much fruit.", "fruits-skill-pass-3", "s.mode == Mode.CATCH and 3 <= s.map.stars < 4 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- Pass any 3 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Hyperdash ON!", "Time and distance is no obstacle to you.", "fruits-skill-pass-4", "s.mode == Mode.CATCH and 4 <= s.map.stars < 5 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- Pass any 4 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("It's Raining Fruit", "And you can catch them all.", "fruits-skill-pass-5", "s.mode == Mode.CATCH and 5 <= s.map.stars < 6 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- Pass any 5 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Fruit Ninja", "Legendary techniques.", "fruits-skill-pass-6", "s.mode == Mode.CATCH and 6 <= s.map.stars < 7 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- Pass any 6 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Dreamcatcher", "No fruit, only dreams now.", "fruits-skill-pass-7", "s.mode == Mode.CATCH and 7 <= s.map.stars < 8 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- Pass any 7 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Lord of the Catch", "Your kingdom kneels before you.", "fruits-skill-pass-8", "s.mode == Mode.CATCH and 8 <= s.map.stars < 9 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- Pass any 8 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Catch 20,000 fruits", "That is a lot of dietary fiber.", "fruits-hits-20000", "s.player.play_mode == Mode.CATCH and s.player.total_hits == 20_000"); -- Catch 20,000 fruits. Your profile on the osu! website will show you how many fruits you've caught so far.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Catch 200,000 fruits", "So, I heard you like fruit...", "fruits-hits-200000", "s.player.play_mode == Mode.CATCH and s.player.total_hits == 200_000"); -- Catch 200,000 fruits. Your profile on the osu! website will show you how many fruits you've caught so far.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Catch 2,000,000 fruits", "Downright healthy.", "fruits-hits-2000000", "s.player.play_mode == Mode.CATCH and s.player.total_hits == 2_000_000"); -- Catch 2,000,000 fruits. Your profile on the osu! website will show you how many fruits you've caught so far.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Catch 20,000,000 fruits", "Nothing left behind.", "fruits-hits-20000000", "s.player.play_mode == Mode.CATCH and s.player.total_hits == 20_000_000"); -- Catch 20,000,000 fruits. Your profile on the osu! website will show you how many fruits you've caught so far.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Keystruck", "The beginning of a new story.", "mania-skill-fc-1", "s.mode == Mode.MANIA and s.perfect and 1 <= s.map.stars < 2 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- FC any 1 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Keying In", "Finding your groove.", "mania-skill-fc-2", "s.mode == Mode.MANIA and s.perfect and 2 <= s.map.stars < 3 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- FC any 2 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Hyperflow", "You can *feel* the rhythm.", "mania-skill-fc-3", "s.mode == Mode.MANIA and s.perfect and 3 <= s.map.stars < 4 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- FC any 3 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Breakthrough", "Many skills mastered, rolled into one.", "mania-skill-fc-4", "s.mode == Mode.MANIA and s.perfect and 4 <= s.map.stars < 5 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- FC any 4 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Everything Extra", "Giving your all is giving everything you have.", "mania-skill-fc-5", "s.mode == Mode.MANIA and s.perfect and 5 <= s.map.stars < 6 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- FC any 5 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Level Breaker", "Finesse beyond reason.", "mania-skill-fc-6", "s.mode == Mode.MANIA and s.perfect and 6 <= s.map.stars < 7 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- FC any 6 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Step Up", "A precipice rarely seen.", "mania-skill-fc-7", "s.mode == Mode.MANIA and s.perfect and 7 <= s.map.stars < 8 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- FC any 7 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Behind The Veil", "Supernatural!", "mania-skill-fc-8", "s.mode == Mode.MANIA and s.perfect and 8 <= s.map.stars < 9 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- FC any 8 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("First Steps", "It isn't 9-to-5, but 1-to-9. Keys, that is.", "mania-skill-pass-1", "s.mode == Mode.MANIA and 1 <= s.map.stars < 2 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- Pass any 1 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("No Normal Player", "Not anymore, at least.", "mania-skill-pass-2", "s.mode == Mode.MANIA and 2 <= s.map.stars < 3 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- Pass any 2 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Impulse Drive", "Not quite hyperspeed, but getting close.", "mania-skill-pass-3", "s.mode == Mode.MANIA and 3 <= s.map.stars < 4 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- Pass any 3 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Hyperspeed", "Woah.", "mania-skill-pass-4", "s.mode == Mode.MANIA and 4 <= s.map.stars < 5 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- Pass any 4 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Ever Onwards", "Another challenge is just around the corner.", "mania-skill-pass-5", "s.mode == Mode.MANIA and 5 <= s.map.stars < 6 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- Pass any 5 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Another Surpassed", "Is there no limit to your skills?", "mania-skill-pass-6", "s.mode == Mode.MANIA and 6 <= s.map.stars < 7 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- Pass any 6 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Extra Credit", "See me after class.", "mania-skill-pass-7", "s.mode == Mode.MANIA and 7 <= s.map.stars < 8 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- Pass any 7 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Maniac", "There's just no stopping you.", "mania-skill-pass-8", "s.mode == Mode.MANIA and 8 <= s.map.stars < 9 and not s.mods.has_any(Mods.EASY, Mods.NOFAIL, Mods.HALFTIME)"); -- Pass any 8 star map (calculated with mods) without using EZ/NF/HT mods.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("40,000 Keys", "Just the start of the rainbow.", "mania-hits-40000", "s.player.play_mode == Mode.MANIA and s.player.total_hits == 40_000"); -- Reach 40,000 key hits. Your profile on the osu! website will show you how many keys you've hit so far.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("400,000 Keys", "Four hundred thousand and still not even close.", "mania-hits-400000", "s.player.play_mode == Mode.MANIA and s.player.total_hits == 400_000"); -- Reach 400,000 key hits. Your profile on the osu! website will show you how many keys you've hit so far.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("4,000,000 Keys", "Is this the end of the rainbow?", "mania-hits-4000000", "s.player.play_mode == Mode.MANIA and s.player.total_hits == 4_000_000"); -- Reach 4,000,000 key hits. Your profile on the osu! website will show you how many keys you've hit so far.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("40,000,000 Keys", "When someone asks which keys you play, the answer is now 'yes'.", "mania-hits-40000000", "s.player.play_mode == Mode.MANIA and s.player.total_hits == 40_000_000"); -- Reach 40,000,000 key hits. Your profile on the osu! website will show you how many keys you've hit so far.
INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Twin Perspectives", "You met Mani and Mari, our twin osu!mania mascots.", "mania-secret-meganekko", "s.mode == Mode.MANIA and s.max_combo >= 100"); -- Pass any mania map with 100 combo or more.


-- All of these achievements, are ones we either can't implement or don't want to.
-- INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("The Firmament Moves", "Number fourteen? More like number one.", "all-secret-celestialmovement", ""); -- Pass any difficulty of cYsmix - Moonlight Sonata, using any combination of at least 3 of the 4 mods above, that is 3*+ after mods. NOTE: You may do this on either mapset listed.
-- INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Hospitality", "Welcome.", "all-secret-hospitality", ""); -- Play a guest difficulty of any mapper, then pass a different map by the same mapper. Using NF is not allowed, despite the category the medal is in. NOTE: The second map you play can be any map, guest diff or host diff, but the first one must be specifically a guest difficulty.
-- INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("True North", "Where they tread, you go.", "all-secret-true-north", ""); -- Play 10 maps in a row from the same mapper. All plays must be on different beatmap sets. Difficulty reduction mods, including NF, are allowed. NOTE: Guest difficulties count for the person credited for mapping it, not for the host of the mapset.
-- INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Superfan", "THIS IS MY JAM.", "all-secret-superfan", ""); -- Play 10 maps in a row from the same artist. All plays must be on different beatmap sets. Difficulty reduction mods, including NF, are allowed.
-- INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("You're Here Forever", "We knew you'd be back.", "all-secret-youre-here-forever", ""); -- Pass any map in any gamemode after not having played that gamemode for 2 or more weeks. Difficulty reduction mods, including NF, are allowed. NOTE: You must have over 2,500 playcount in the gamemode that you play upon coming back, otherwise it will not work. NOTE: Make sure your submitted play is a pass (no restarts), otherwise the fail will count as a submitted play, and you will have to wait another 2 weeks.
-- INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Time Sink", "Rise from the depths into a new age.", "all-secret-time-sink", ""); -- Submit a score on both awp's 2009 and Camo's 2021 mapsets of Alestorm - Keelhauled (in a row, in that order). Difficulty reduction mods, including NF, are allowed. NOTE: You MUST get the scores back-to-back, and the second one must be a pass; if you fail at any point on the second map, you must restart the medal from the beginning.
-- INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Dead Center", "As all things should be.", "all-secret-deadcenter", ""); -- FC any 3*+ map that has an equal amount of circles and sliders.
-- INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Creator's Gambit", "I made this.", "all-secret-trophy", ""); -- Pass any Ranked, Qualified, or Loved map which was made by yourself. NOTE: Guest difficulties count for the person credited for mapping it, not for the host of the mapset.
-- INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Obsessed", "COMPLETION AT ALL COSTS.", "all-secret-obsessed", ""); -- Retry a map 100 times, and then pass it. NOTE: Each 'retry' must have at least 10,000 score for it to count as a play.
-- INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Jack of All Trades", "Good at everything.", "all-secret-jack", ""); -- Get 5000+ playcount in each of the four gamemodes (standard / taiko / mania / catch the beat).
-- INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("I Can See The Top", "Your dedication has paid off. Welcome to the top 50,000!", "all-skill-highranker-1", "s.player.rank < 50_000"); -- Reach at least rank 50,000 in the pp rankings of any gamemode.
-- INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("All Good", "Better now, thanks!", "all-secret-allgood", ""); -- Set two scores on Carpool Tunnel - Better Now in a row. Difficulty reduction mods, including NF, are allowed. NOTE: If you decide to use mods, you must use the same mods on both scores.
-- INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Replica", "One just like the other.", "all-secret-replica", ""); -- Get the same accuracy on two different difficulties of Zekk - Duplication. NOTE: Both plays must be on the same mapset and in the same gamemode. NOTE: This medal can only be achieved on the beatmaps to the right; no other ranked beatmapsets of Duplication can give you this medal.
-- INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Right On Time", "The first minute is always the hardest.", "all-secret-rightontime", ""); -- Submit a score on Kola Kid - timer on the first minute of any hour (ex: 5:00pm, 6:00pm). NOTE: The play must END at this time, so make sure to time this properly! For example, a DT play will need to be started in the first half of :59, not started at :00. NOTE: The 'seconds' on the play do not matter, as long as you are within minute :00 of the hour. 
-- INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Mad Scientist", "The experiment... it's all gone!", "all-secret-madscientist", ""); -- Pass every difficulty of Thank You Scientist - Mr. Invisible, using HD. NOTE: Using DT is allowed. Using NF is not allowed, despite the category the medal is in.
-- INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("The Sum Of All Fears", "Unfortunate.", "all-secret-nuked", ""); -- FC any map, but miss the very last (or very first) note.
-- INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Aeon", "In the mire of thawing time, memory shall be your guide.", "all-secret-aeon", ""); -- FC any map that was ranked in 2011 or earlier, using the mods above. The map must be at least 4* and at least 3 minutes long after mods.
-- INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Tribulation", "Success is inevitable... eventually.", "all-secret-tribulation", ""); -- Pass any map that you have 100+ playcount on and have not passed yet. NOTE: Due to some coding weirdness, if you go to a map you have over 100 playcount on, and play that difficulty in a converted gamemode (e.x. a standard map on taiko), it will count.
-- INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Is This Real Life?", "You did NOT just pull that off.", "osu-secret-supersuperhardhddt", ""); -- FC any map that is at least AR11, OD10+DT, HP10+DT, and 240BPM or over. NOTE: The map must be at least AR7.2, OD7.2, HP7.2, and 160BPM before mods, and you must use DT and HR (+HD, optionally).
-- INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Unstoppable", "Holy shit.", "osu-secret-superhardhddt", ""); -- Pass any map that is at least AR11, OD10+DT, HP10+DT, and 240BPM or over. NOTE: The map must be at least AR7.2, OD7.2, HP7.2, and 160BPM before mods, and you must use DT and HR (+HD, optionally).
-- INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Iron Will", "A legacy of broken bonds, remade.", "all-secret-iron-will", ""); -- Pass all of the osu! World Cup Grand Finals custom tiebreaker maps from 2020 to 2022.
-- INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("S-Ranker", "Accuracy is really underrated.", "all-secret-rank-s", ""); -- Get five S (or SS) ranks on different maps within 24 hours. NOTE: S+ and SS+ ranks (silver S and SS ranks, which are done when using HD or FL) also work.
-- INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Internment", "Stained in the hues of madness, they rage within a four-walled jail.", "osu-secret-internment", ""); -- On any 'Insane' difficulty (4.0* - 5.29*) of Frums - theyaremanycolors, set three plays in a row that have combos equal to the R, G, and B values of the difficulty indicator (on the osu! website) for the map you are playing. The possible combinations are as follows:  .ict th,td{padding:5px; border-bottom: 1px solid rgb(var(--accent));}.ict{border: 2px solid rgb(var(--accent)); background-color: rgb(var(--accentdark)); border-collapse: collapse;}PlayCombo (vanchanicalinsane)Combo (celinsane)1st255x243x2nd104x76x3rd108x133x You can find an explanation to the solution in the pinned comments below. NOTE: You MUST get the scores back-to-back, and the third one must be a pass; if you overcombo at any point on the second or third play, fail the third play, or fail to reach the max combo requirement for the second or third score, you must restart the medal from the beginning. NOTE: Difficulty reduction mods and failing are both allowed for the first two plays, despite the category the medal is in.
-- INSERT INTO `achievements` (`name`, `description`, `icon`, `condition`) VALUES ("Most Improved", "Now THAT is improvement.", "all-secret-improved", ""); -- Get a D rank with more than 100,000 score, and then get an A rank or better on the same map within 24 hours after that play. Difficulty reduction mods, including NF, are allowed.